apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pgadmin.fullname" . }}
  labels:
    {{- include "pgadmin.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "pgadmin.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pgadmin.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "pgadmin.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: {{ .Values.env.PGADMIN_DEFAULT_EMAIL | quote }}
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "pgadmin.secretName" . }}
                  key: {{ .Values.secrets.passwordKey }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP 