apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pgvector
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/REPLACE_ORG/REPLACE_REPO.git
    targetRevision: main
    path: llama-stack-demo-working/deployment/pgvector
    helm:
      releaseName: pgvector
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: llama-stack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
