apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: redhat-keycloak
  labels:
    app: keycloak
spec:
  instances: 1
  hostname:
    hostname: keycloak-admin.apps.cluster-95nrt.95nrt.sandbox5429.opentlc.com
    strict: false
    strictBackchannel: false
  http:
    httpEnabled: true
  db:
    vendor: postgres
    host: postgresql
    port: 5432
    database: keycloak
    usernameSecret:
      name: postgresql-credentials
      key: username
    passwordSecret:
      name: postgresql-credentials
      key: password
  additionalOptions:
    - name: proxy
      value: edge
    - name: hostname-strict
      value: "false"
    - name: hostname-strict-https
      value: "false"
