apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: keycloak-realm-import
  namespace: redhat-keycloak
spec:
  keycloakCRName: keycloak
  realm:
    realm: "demo-realm"
    displayName: "Demo Realm"
    enabled: true
    loginWithEmailAllowed: true
    duplicateEmailsAllowed: false
    resetPasswordAllowed: true
    editUsernameAllowed: false
    bruteForceProtected: true
    permanentLockout: false
    maxFailureWaitSeconds: 900
    minimumQuickLoginWaitSeconds: 60
    waitIncrementSeconds: 60
    maxDeltaTimeSeconds: 43200
    failureFactor: 30
    defaultRoles:
      - "offline_access"
      - "uma_authorization"
    clients:
      - clientId: "demo-client"
        name: "Demo Client"
        description: "Demo application client"
        enabled: true
        clientAuthenticatorType: "client-secret"
        secret: "CHANGE_ME_IN_PRODUCTION"
        # ⚠️ NOTE: This is a development-only client secret.
        # Generate a secure random secret for production use!
        standardFlowEnabled: true
        implicitFlowEnabled: false
        directAccessGrantsEnabled: true
        serviceAccountsEnabled: true
        publicClient: false
        protocol: "openid-connect"
        attributes:
          "saml.assertion.signature": "false"
          "saml.force.post.binding": "false"
          "saml.multivalued.roles": "false"
          "saml.encrypt": "false"
          "saml.server.signature": "false"
          "saml.server.signature.keyinfo.ext": "false"
          "exclude.session.state.from.auth.response": "false"
          "saml_force_name_id_format": "false"
          "saml.client.signature": "false"
          "tls.client.certificate.bound.access.tokens": "false"
          "saml.authnstatement": "false"
          "display.on.consent.screen": "false"
          "saml.onetimeuse.condition": "false"
        redirectUris:
          - "http://localhost:8080/*"
          - "https://localhost:8443/*"
        webOrigins:
          - "http://localhost:8080"
          - "https://localhost:8443"
        defaultClientScopes:
          - "web-origins"
          - "role_list"
          - "profile"
          - "roles"
          - "email"
        optionalClientScopes:
          - "address"
          - "phone"
          - "offline_access"
          - "microprofile-jwt"
    users:
      - username: "demo-user"
        enabled: true
        emailVerified: true
        email: "demo-user@example.com"
        firstName: "Demo"
        lastName: "User"
        credentials:
          - type: "password"
            value: "dummy"
            temporary: true
            # NOTE: User password is set to "dummy" for development
            # Password is temporary - user must change on first login!
        realmRoles:
          - "offline_access"
          - "uma_authorization"
        clientRoles:
          demo-client:
            - "view-profile"
            - "manage-account"
    roles:
      realm:
        - name: "demo-role"
          description: "Demo role for testing"
          composite: false
          clientRole: false
