apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: llama-stack-playground-build-is
  namespace: llama-stack
  labels:
    app: llama-stack-playground
    component: build
spec:
  triggers:
    - type: ConfigChange
  
  # Output to ImageStream (internal registry)
  output:
    to:
      kind: ImageStreamTag
      name: llama-stack-playground:release-0.3.0-v1
  
  resources:
    limits:
      cpu: "2"
      memory: 4Gi
    requests:
      cpu: "1"
      memory: 2Gi
  
  successfulBuildsHistoryLimit: 3
  failedBuildsHistoryLimit: 3
  
  # Docker build strategy - will build for amd64 automatically
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Containerfile
  
  # Binary source - upload from local directory
  source:
    type: Binary
    binary: {}
  
  runPolicy: Serial

