apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: llama-stack

resources:
  - secret.yaml
  - serviceaccount.yaml
  - service.yaml
  - statefulset.yaml
  - create-vector-extension-job.yaml
