apiVersion: v1
kind: Service
metadata:
  name: pgvector
  labels:
    app.kubernetes.io/name: pgvector
    app.kubernetes.io/instance: pgvector
spec:
  ports:
    - port: 5432
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    app.kubernetes.io/name: pgvector
    app.kubernetes.io/instance: pgvector
  type: ClusterIP
