kind: ConfigMap
apiVersion: v1
metadata:
  name: llama-stack-config
data:
  run.yaml: |
    version: '2'
    image_name: remote-vllm
    apis:
    - agents
    - datasetio
    - eval
    - inference
    - safety
    - scoring
    - tool_runtime
    - vector_io
    providers:
      inference:
      - provider_id: llama-3b
        provider_type: remote::vllm
        config:
          url: ${env.LLAMA3B_URL}
          max_tokens: 128000
          api_token: ${env.LLAMA_TOKEN}
          tls_verify: false
      - provider_id: llama-17b
        provider_type: remote::vllm
        config:
          url: ${env.LLAMA17B_URL}
          max_tokens: 128000
          api_token: ${env.LLAMA17B_TOKEN}
          tls_verify: false
      - provider_id: deepseek
        provider_type: remote::vllm
        config:
          url: ${env.DEEPSEEK_URL}
          max_tokens: 128000
          api_token: ${env.DEEPSEEK_TOKEN}
          tls_verify: false          
      - provider_id: sentence-transformers
        provider_type: inline::sentence-transformers
        config: {}
      vector_io:
      - provider_id: milvus
        provider_type: inline::milvus
        config:
          db_path: ${env.SQLITE_STORE_DIR:~/.llama/distributions/rh}/milvus.db
          kvstore:
            type: sqlite
            db_path: ${env.SQLITE_STORE_DIR:~/.llama/distributions/rh}/milvus_registry.db
        module: null
      agents:
      - provider_id: meta-reference
        provider_type: inline::meta-reference
        config:
          persistence_store:
            type: sqlite
            namespace: null
            db_path: ${env.SQLITE_STORE_DIR:~/.llama/distributions/rh}/agents_store.db
          responses_store:
            type: sqlite
            namespace: null
            db_path: ${env.SQLITE_STORE_DIR:~/.llama/distributions/rh}/responses_store.db            
      eval:
      - provider_id: meta-reference
        provider_type: inline::meta-reference
        config:
          kvstore:
            type: sqlite
            namespace: null
            db_path: ${env.SQLITE_STORE_DIR:~/.llama/distributions/rh}/meta_reference_eval.db
      datasetio:
      - provider_id: huggingface
        provider_type: remote::huggingface
        config:
          kvstore:
            type: sqlite
            namespace: null
            db_path: ${env.SQLITE_STORE_DIR:~/.llama/distributions/rh}/huggingface_datasetio.db
      - provider_id: localfs
        provider_type: inline::localfs
        config:
          kvstore:
            type: sqlite
            namespace: null
            db_path: ${env.SQLITE_STORE_DIR:~/.llama/distributions/rh}/localfs_datasetio.db
      scoring:
      - provider_id: basic
        provider_type: inline::basic
        config: {}
      - provider_id: llm-as-judge
        provider_type: inline::llm-as-judge
        config: {}
      - provider_id: braintrust
        provider_type: inline::braintrust
        config:
          openai_api_key: ${env.OPENAI_API_KEY:}
      tool_runtime:
      - provider_id: brave-search
        provider_type: remote::brave-search
        config:
          api_key: ${env.BRAVE_SEARCH_API_KEY:}
          max_results: 3
      - provider_id: tavily-search
        provider_type: remote::tavily-search
        config:
          api_key: ${env.TAVILY_SEARCH_API_KEY:}
          max_results: 3
      - provider_id: rag-runtime
        provider_type: inline::rag-runtime
        config: {}
      - provider_id: model-context-protocol
        provider_type: remote::model-context-protocol
        config: {}
    metadata_store:
      type: sqlite
      db_path: ${env.SQLITE_STORE_DIR:~/.llama/distributions/rh}/registry.db
    models:
    - metadata: {}
      model_id: ${env.LLAMA3B_MODEL}
      provider_id: llama-3b
      model_type: llm    
    - metadata: {}
      model_id: ${env.LLAMA17B_MODEL}
      provider_id: llama-17b
      model_type: llm
    - metadata: {}
      model_id: ${env.DEEPSEEK_MODEL}
      provider_id: deepseek
      model_type: llm      
    - metadata:
        embedding_dimension: 384
      model_id: all-MiniLM-L6-v2
      provider_id: sentence-transformers
      model_type: embedding
    vector_dbs: []
    datasets: []
    scoring_fns: []
    benchmarks: []
    tool_groups:
    - toolgroup_id: builtin::websearch
      provider_id: tavily-search
    - toolgroup_id: builtin::rag
      provider_id: rag-runtime
    - toolgroup_id: mcp::openshift
      provider_id: model-context-protocol
      mcp_endpoint:
        uri: "http://ocp-mcp-server:8000/sse"
    - toolgroup_id: mcp::slack
      provider_id: model-context-protocol
      mcp_endpoint:
        uri: "http://slack-mcp-server:80/sse"
    - toolgroup_id: mcp::atlassian
      provider_id: model-context-protocol
      mcp_endpoint:
        uri: "http://atlassian-mcp-server:8080/sse"