---
apiVersion: llamastack.io/v1alpha1
kind: LlamaStackDistribution
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"llamastack.io/v1alpha1","kind":"LlamaStackDistribution","metadata":{"annotations":{},"name":"llamastack-with-config","namespace":"default"},"spec":{"replicas":1,"server":{"containerSpec":{"port":8321},"distribution":{"name":"remote-vllm"},"userConfig":{"configMapName":"llama-stack-config"}}}}
  name: llamastack-with-config
spec:
  replicas: 1
  server:
    containerSpec:
      command:
        - /bin/sh
        - '-c'
        - llama stack run /etc/llama-stack/run.yaml
      env:
        - name: LLAMA3B_URL
          value: 'https://llama-3-2-3b-maas-apicast-production.apps.prod.rhoai.rh-aiservices-bu.com:443/v1'
        - name: LLAMA3B_MODEL
          value: llama-3-2-3b
        - name: LLAMA_TOKEN
          valueFrom:
            secretKeyRef:
              name: llama-stack-secret
              key: llama-token
        - name: LLAMA17B_URL
          value: 'https://llama-4-scout-17b-16e-w4a16-maas-apicast-production.apps.prod.rhoai.rh-aiservices-bu.com:443/v1'
        - name: LLAMA17B_MODEL
          value: llama-4-scout-17b-16e-w4a16
        - name: LLAMA17B_TOKEN
          valueFrom:
            secretKeyRef:
              name: llama-stack-secret
              key: llama17b-token
        - name: DEEPSEEK_URL
          value: 'https://deepseek-r1-qwen-14b-w4a16-maas-apicast-production.apps.prod.rhoai.rh-aiservices-bu.com:443/v1'
        - name: DEEPSEEK_MODEL
          value: r1-qwen-14b-w4a16
        - name: DEEPSEEK_TOKEN
          valueFrom:
            secretKeyRef:
              name: llama-stack-secret
              key: deepseek-token      
        - name: MILVUS_DB_PATH
          value: ~/.llama/milvus.db
        - name: FMS_ORCHESTRATOR_URL
          value: 'http://localhost'
        - name: LLAMA_STACK_CONFIG_DIR
          value: /opt/app-root/src/.llama/distributions/rh/
        - name: PGVECTOR_HOST
          valueFrom:
            secretKeyRef:
              name: pgvector-secret
              key: pgvector-host
        - name: PGVECTOR_PORT
          valueFrom:
            secretKeyRef:
              name: pgvector-secret
              key: pgvector-port
        - name: PGVECTOR_DB
          valueFrom:
            secretKeyRef:
              name: pgvector-secret
              key: pgvector-db
        - name: PGVECTOR_USER
          valueFrom:
            secretKeyRef:
              name: pgvector-secret
              key: pgvector-user
        - name: PGVECTOR_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pgvector-secret
              key: pgvector-password
        - name: SENTENCE_TRANSFORMERS_HOME
          value: /opt/app-root/src/.cache/huggingface/hub
        - name: HF_HUB_OFFLINE
          value: "1"
        - name: TRANSFORMERS_OFFLINE
          value: "1"
        - name: HF_DATASETS_OFFLINE
          value: "1"
      name: llama-stack
      port: 8321
      resources:
        limits:
          cpu: '2'
          memory: 12Gi
        requests:
          cpu: 250m
          memory: 500Mi
    distribution:
      image: registry.redhat.io/rhoai/odh-llama-stack-core-rhel9@sha256:13ec5c9b96a9ca8c0a1fcc0568cf6f893478742d28d3b1381f073b9bdafb3320
    userConfig:
      configMapName: llama-stack-config