# Default values for pgadmin.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: dpage/pgadmin4
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 80

route:
  enabled: true
  host: pgadmin.apps.example.com
  tls:
    enabled: true
    termination: edge

env:
  PGADMIN_DEFAULT_EMAIL: ""

secrets:
  # Name of the secret to use for the pgAdmin password.
  # If empty, a new secret will be created.
  existingSecret: ""
  # The key in the secret that contains the password
  passwordKey: "password"
  # If creating a new secret, this password will be used.
  password: "" 