---
apiVersion: v1
kind: Service
metadata:
  name: atlassian-mcp-server
spec:
  selector:
    app: atlassian-mcp-server
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
